### PR TITLE
add Persian version of DevOps Engineer

### PR DESCRIPTION
**Pull request by mshahmalaki**

### CODE REVIEW

**Comment by AntonyCanut** [comment]
If you want to add your name as translator, welcome ! :)

**Comment by mshahmalaki** [comment]
Yes, it's kind of you, I appreciate it. Thanks.
Where do I add my name in this document?
what is your suggestion?

**Comment by AntonyCanut** [comment]
I suggest in a top under mine, something like "translated by [your name]" but in the document language. You can use the same object to maintain the design.

I think your effort and time must be visible.

Past it on every pages, when the people share the document, they can remember you with that.

**Comment by AntonyCanut** [comment]
Thank you for your work ! :)

**Pull request merged**
